<?php

namespace AppBundle\Repository;

/**
 * AcceptedWoofRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcceptedWoofRepository extends \Doctrine\ORM\EntityRepository
{
}
